export const POST_DATA_REQUEST = "POST_DATA_REQUEST";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILURE = "POST_DATA_FAILURE";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const TITLE_WORD_COUNT = "TITLE_WORD_COUNT";
export const BODY_WORD_COUNT = "BODY_WORD_COUNT";
